version: '3'

services:
  backend:
    build:
      context: ./Backend 
    ports:
      - '8000:8000'
    environment:
      - MONGODB_URI=mongodb+srv://ParandhamaCapstone:sunny%40123@capstone.wikcwwo.mongodb.net/ParandhamaReddy?retryWrites=true&w=majority&appName=Capstone
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    ports:
      - '3000:80'

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
